// WebContent/resources/js/scheduler-4.2.1/examples/frameworks/react/javascript/custom-event-editor/src/App.js
/**
 * Application file
 */
import React, { Fragment, useState, useRef, useCallback, useEffect } from 'react';

import { BryntumScheduler, BryntumDemoHeader, BryntumThemeCombo } from '@bryntum/scheduler-react';
import Popup from './components/Popup';
import { schedulerConfig } from './AppConfig'
import './App.scss';

function App() {
    const scheduler = useRef();

    const [popupShown, showPopup] = useState(false);
    const [eventRecord, setEventRecord] = useState(null);
    const [eventStore, setEventStore] = useState(null);
    const [resourceStore, setResourceStore] = useState(null);

    useEffect(() => {
        const { eventStore, resourceStore } = scheduler.current.instance;
        setEventStore(eventStore);
        setResourceStore(resourceStore);
    }, []);

    const showEditor = useCallback(eventRecord => {
        setEventRecord(eventRecord);
        showPopup(true);
    }, []);

    const hideEditor = useCallback(() => {
        setEventRecord(null);
        showPopup(false);
    }, []);

    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-custom-event-editor"
                title="Bryntum Scheduler Custom React Event Editor demo"
                children={<BryntumThemeCombo />}
            />
            <BryntumScheduler ref={scheduler} {...schedulerConfig} listeners={{
                beforeEventEdit: source => {
                    source.eventRecord.resourceId = source.resourceRecord.id;
                    showEditor(source.eventRecord);
                    return false;
                }
            }} />
            <div>
                {popupShown ? (
                    <Popup
                        text="Popup text"
                        closePopup={hideEditor}
                        eventRecord={eventRecord}
                        eventStore={eventStore}
                        resourceStore={resourceStore}
                    ></Popup>
                ) : null}
            </div>
        </Fragment>
    );
}

export default App;

// WebContent/resources/js/scheduler-4.2.1/examples/frameworks/vue/javascript/custom-event-editor/src/App.vue
<!-- Application -->
<template>
    <v-app>
        <bryntum-demo-header
            title="Vue Custom Event Editor demo"
            link="../../../../../#example-frameworks-vue-javascript-custom-event-editor"
        />
        <bryntum-scheduler
            ref="scheduler"
            v-bind="schedulerConfig"
            :listeners="listeners"
        />
        <event-editor
            v-model="showEditor"
            :eventRecord="eventRecord"
            :eventStore="eventStore"
            :resourceId="resourceId"
            @close="onCloseEditor"
        />
    </v-app>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader
} from '@bryntum/scheduler-vue';
import { schedulerConfig } from './AppConfig';
import EventEditor from './components/EventEditor.vue';

export default {
    name: 'App',

    components: {
        BryntumDemoHeader,
        BryntumScheduler,
        EventEditor
    },

    data() {
        return {
            schedulerConfig,
            showEditor  : false,
            eventRecord : null,
            eventStore  : null,
            resourceId  : null,
            listeners   : {
                beforeEventEdit : this.beforeEventEditHandler
            }
        };
    },

    methods: {
        beforeEventEditHandler(event) {
            this.openEditor(event);
            return false;
        },

        openEditor({ source, resourceRecord, eventRecord }) {
            Object.assign(this, {
                eventStore: source.eventStore,
                resourceId: resourceRecord.id,
                eventRecord: eventRecord,
                showEditor: true
            });
        },

        onCloseEditor() {
            const scheduler = this.$refs.scheduler.instance;
            if (scheduler) {
                scheduler.refresh();
            }
        }
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>
