// WebContent/resources/js/scheduler-4.2.1/examples/frameworks/vue/javascript/pdf-export/src/App.vue
<!-- Application -->
<template>
    <div id="app">
        <bryntum-demo-header
            title="Vue PDF export demo"
            link="../../../../../#example-frameworks-vue-javascript-pdf-export"
        />
        <div class="demo-toolbar align-right">
            <bryntum-button
                cls="b-deep-orange b-raised"
                text="Export"
                @click="exportHandler"
            />
        </div>
        <bryntum-scheduler ref="scheduler" v-bind="schedulerConfig" />
    </div>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader,
    BryntumButton
} from '@bryntum/scheduler-vue';
import { schedulerConfig } from './AppConfig.js';

export default {
    name: 'App',

    components: {
        BryntumDemoHeader,
        BryntumScheduler,
        BryntumButton
    },

    data() {
        return {
            schedulerConfig
        };
    },

    methods: {
        exportHandler() {
            this.$refs.scheduler.instance.features.pdfExport.showExportDialog();
        }
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>

// WebContent/resources/js/scheduler-4.2.1/examples/frameworks/angular/pdf-export/src/app/app.component.ts
/**
 * app component script
 */
import { Component, ViewChild } from '@angular/core';
import { BryntumSchedulerComponent } from '@bryntum/scheduler-angular';
import { Scheduler } from '@bryntum/scheduler/scheduler.lite.umd.js';
import { schedulerConfig } from './app.config';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})
export class AppComponent {
    public schedulerConfig: any = schedulerConfig;
    private scheduler: Scheduler;

    @ViewChild(BryntumSchedulerComponent, { static : true }) schedulerComponent: BryntumSchedulerComponent;

    ngAfterViewInit(): void {
        // Store Scheduler instance
        this.scheduler = this.schedulerComponent.instance;
    }

    onExportClick(): void {
        this.scheduler.features['pdfExport'].showExportDialog();
    }
}

<bryntum-demo-header
    link = "../../../../../#example-frameworks-angular-pdf-export"
    title = "Angular PDF Export demo"
></bryntum-demo-header>

<div class = "demo-toolbar align-right">
    <bryntum-button
        cls = "b-skip-test b-deep-orange b-raised"
        text = "Export"
        (onClick) = "onExportClick()"
    ></bryntum-button>
</div>

<bryntum-scheduler
    #scheduler
    [barMargin] = "schedulerConfig.barMargin"
    [columns] = "schedulerConfig.columns"
    [crudManager] = "schedulerConfig.crudManager"
    [dependenciesFeature] = "schedulerConfig.dependenciesFeature"
    [endDate] = "schedulerConfig.endDate"
    [eventColor] = "schedulerConfig.eventColor"
    [eventDragFeature] = "schedulerConfig.eventDragFeature"
    [eventRenderer] = "schedulerConfig.eventRenderer"
    [eventStyle] = "schedulerConfig.eventStyle"
    [pdfExportFeature] = "schedulerConfig.pdfExportFeature"
    [rowHeight] = "schedulerConfig.rowHeight"
    [startDate] = "schedulerConfig.startDate"
    [stripeFeature] = "schedulerConfig.stripeFeature"
    [timeRangesFeature] = "schedulerConfig.timeRangesFeature"
    [viewPreset] = "schedulerConfig.viewPreset"
></bryntum-scheduler>
