// WebContent/resources/js/scheduler-4.2.1/examples/frameworks/vue/javascript/dependencies/src/App.vue
<!--
/**
 * Application implementation
 */
 -->
<template>
    <div id="container">
        <bryntum-demo-header
            title="Vue Dependencies demo"
            link="../../../../../#example-frameworks-vue-javascript-dependencies"
        />
        <bryntum-scheduler ref="scheduler" v-bind="schedulerConfig" />
    </div>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader
} from '@bryntum/scheduler-vue';
import { schedulerConfig } from './AppConfig';

export default {
    name: 'app',

    components: {
        BryntumDemoHeader,
        BryntumScheduler
    },

    data() {
        return {
            schedulerConfig
        };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>

// WebContent/resources/js/scheduler-4.2.1/examples/frameworks/react/javascript/dependencies/src/App.js
/**
 * The App file. It should stay as simple as possible
 */
import React, { Fragment } from 'react';
import {
    BryntumScheduler,
    BryntumDemoHeader,
    BryntumThemeCombo
} from '@bryntum/scheduler-react';
import { schedulerConfig } from './AppConfig';
import './App.scss';

const App = () => {
    return (
        <Fragment>
            <BryntumDemoHeader
                title="React Dependencies demo"
                href="../../../../../#example-frameworks-react-javascript-dependencies"
                children={<BryntumThemeCombo />}
            />
            <BryntumScheduler {...schedulerConfig} />
        </Fragment>
    );
};

export default App;
