// WebContent/resources/js/scheduler-4.2.1/examples/frameworks/react/javascript/dependencies/src/App.js
/**
 * The App file. It should stay as simple as possible
 */
import React, { Fragment } from 'react';
import {
    BryntumScheduler,
    BryntumDemoHeader,
    BryntumThemeCombo
} from '@bryntum/scheduler-react';
import { schedulerConfig } from './AppConfig';
import './App.scss';

const App = () => {
    return (
        <Fragment>
            <BryntumDemoHeader
                title="React Dependencies demo"
                href="../../../../../#example-frameworks-react-javascript-dependencies"
                children={<BryntumThemeCombo />}
            />
            <BryntumScheduler {...schedulerConfig} />
        </Fragment>
    );
};

export default App;

// WebContent/resources/js/scheduler-4.2.1/examples/frameworks/vue/javascript/simple/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <bryntum-demo-header
            title="Vue Simple demo"
            link="../../../../../#example-frameworks-vue-javascript-simple"
        />
        <div class="demo-toolbar align-right">
            <bryntum-checkbox
                text="Stripe Feature"
                :checked="false"
                @action="handleToggle($event, 'stripe')"
            />
            <bryntum-checkbox
                text="Column Lines Feature"
                :checked="true"
                @action="handleToggle($event, 'columnLines')"
            />
        </div>
        <bryntum-scheduler
            ref="scheduler"
            v-bind="schedulerConfig"
            :stripeFeature="stripe"
            :columnLinesFeature="columnLines"
        />
    </div>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader,
    BryntumCheckbox
} from "@bryntum/scheduler-vue";
import { schedulerConfig } from "./AppConfig.js";

export default {
    name: "App",

    components: {
        BryntumDemoHeader,
        BryntumScheduler,
        BryntumCheckbox
    },

    methods: {
        handleToggle({ checked }, feature) {
            this[feature] = { disabled: !checked };
        }
    },

    data() {
        return {
            schedulerConfig,
            stripe: { disabled: true },
            columnLines: { disabled: false }
        };
    }
};
</script>

<style lang="scss">
@import "./App.scss";
</style>
