// WebContent/resources/js/scheduler-4.2.1/examples/frameworks/vue/javascript/dependencies/src/App.vue
<!--
/**
 * Application implementation
 */
 -->
<template>
    <div id="container">
        <bryntum-demo-header
            title="Vue Dependencies demo"
            link="../../../../../#example-frameworks-vue-javascript-dependencies"
        />
        <bryntum-scheduler ref="scheduler" v-bind="schedulerConfig" />
    </div>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader
} from '@bryntum/scheduler-vue';
import { schedulerConfig } from './AppConfig';

export default {
    name: 'app',

    components: {
        BryntumDemoHeader,
        BryntumScheduler
    },

    data() {
        return {
            schedulerConfig
        };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>

// WebContent/resources/js/scheduler-4.2.1/examples/frameworks/react/javascript/vertical/src/App.js
/**
 * The React App file
 */
import React, { Fragment } from 'react';

import { BryntumDemoHeader, BryntumThemeCombo } from '@bryntum/scheduler-react';
import Scheduler from './components/Scheduler';
import './App.scss';

const App = props => {
    const headerConfig = {
        title: 'React Vertical mode demo',
        href: '../../../../../#example-frameworks-react-javascript-vertical'
    };
    return (
        <Fragment>
            <BryntumDemoHeader {...headerConfig} children={<BryntumThemeCombo />} />
            <Scheduler />
        </Fragment>
    );
};

export default App;
