// WebContent/resources/js/scheduler-4.2.1/examples/frameworks/react/javascript/drag-onto-tasks/src/App.js
/**
 * Application
 */
import React, { Fragment, useEffect, useState } from 'react';

import { BryntumDemoHeader, BryntumThemeCombo } from '@bryntum/scheduler-react';
import { AjaxStore, EventStore, Toast } from '@bryntum/scheduler/scheduler.umd';
import Scheduler from './components/Scheduler.js';
import Task from './lib/Task.js';
import EquipmentGrid from './lib/EquipmentGrid.js';
import './App.scss';

const App = () => {
    // we need to pass these three down to scheduler
    // useState prevents creating new instances on each run
    const [equipmentStore] = useState(
        new AjaxStore({
            modelClass: Task,
            readUrl: 'data/equipment.json',
            sorters: [{ field: 'name', ascending: true }]
        })
    );
    const [eventStore] = useState(
        new EventStore({
            modelClass: Task
        })
    );
    const [equipmentGrid] = useState(
        new EquipmentGrid({
            cls: 'equipment',
            eventStore: eventStore,
            // Use a chained Store to avoid its filtering to interfere with Scheduler's rendering
            store: equipmentStore.makeChained(() => true)
        })
    );
    useEffect(() => {
        equipmentGrid.appendTo = 'content';
        equipmentGrid.render();

        Toast.show({
            timeout: 3500,
            html:
                'Please note that this example uses the Bryntum Grid, which is licensed separately.'
        });
    }, [equipmentGrid]);

    return (
        <Fragment>
            <BryntumDemoHeader
                title="React Drag onto Tasks demo"
                href="../../../../../#example-frameworks-react-javascript-drag-onto-tasks"
                children={<BryntumThemeCombo />}
            />
            <div id="content">
                <Scheduler extraData={{ equipmentStore, EquipmentGrid, equipmentGrid }} />
            </div>
        </Fragment>
    );
};

export default App;

// WebContent/resources/js/scheduler-4.2.1/examples/frameworks/vue/javascript/drag-from-grid/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <bryntum-demo-header
            title="Vue Drag from grid demo"
            link="../../../../../#example-frameworks-vue-javascript-drag-from-grid"
        />
        <div class="demo-toolbar align-right">
            <bryntum-button
                tooltip="Toggles whether to automatically reschedule overlapping tasks"
                icon="b-fa b-fa-calendar"
                :toggleable="true"
                text="Auto reschedule"
                @click="onAutoReschedule"
            />
        </div>
        <div class="content-container">
            <bryntum-scheduler
                ref="scheduler"
                v-bind="schedulerConfig"
            />
            <grid ref="grid" :config="gridConfig"></grid>
        </div>
    </div>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader,
    BryntumButton
} from '@bryntum/scheduler-vue';
import { schedulerConfig, gridConfig } from './AppConfig';
import Grid from './components/Grid.vue';
import Drag from './lib/Drag.js';
import { Toast } from '@bryntum/scheduler';

export default {
    name: 'App',

    components: {
        BryntumDemoHeader,
        BryntumScheduler,
        BryntumButton,
        Grid
    },

    data() {
        return {
            schedulerConfig,
            gridConfig
        };
    },

    mounted() {
        const scheduler = this.$refs.scheduler.instance;

        scheduler.eventStore.on({
            update: this.onEventStoreUpdate,
            add: this.onEventStoreAdd,
            thisObj: scheduler
        });

        new Drag({
            grid: this.$refs.grid.grid,
            schedule: this.$refs.scheduler.instance,
            constrain: false,
            outerElement: this.$refs.grid.grid.element
        });

        Toast.show({
            timeout: 3500,
            html:
                'Please note that this example uses the Bryntum Grid, which is licensed separately.'
        });
    },

    methods: {
        // specific to this example - reschedules the tasks
        onEventStoreUpdate({ record }) {
            const scheduler = this.$refs.scheduler.instance;
            if (scheduler.autoRescheduleTasks) {
                scheduler.eventStore.rescheduleOverlappingTasks(
                    record
                );
            }
        },

        // specific to this example - reschedules the tasks
        onEventStoreAdd({ records }) {
            const scheduler = this.$refs.scheduler.instance;
            if (scheduler.autoRescheduleTasks) {
                records.forEach(eventRecord =>
                    scheduler.eventStore.rescheduleOverlappingTasks(
                        eventRecord
                    )
                );
            }
        },
        // specific to this example - toggles auto-rescheuling
        onAutoReschedule({ source: button }) {
            this.$refs.scheduler.instance.autoRescheduleTasks =
                button.pressed;
        }
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>
